### ISSUE TITLE
Идеи процедур/функций/триггеров

### ISSUE THREAD

**Issue by dadyarri** [student-archive/database#8]
1. вычисление результата тестов по истории _[proc]_
2. создание случайной выборки из вопросов _[func]_
3. создание случайной выборки из вариантов ответов _[func]_
4. создания события по результатам тестов _[proc]_

**Comment by ironalex2102** [comment]
5. При появлении нового предммета, появляется пример для заполнения вложений
6. При появлении новой группы создаются автоматом поля для главных людей (эмплои)
7. выводить методички, которые написаны определенным преподом
8. добавить в таб user пол человека, если мужской, то сразу оповещение о справке для военкомата 
9. при создании группы выводить список преподавателей, которые есть на специальности
10. уведомление о скором удалении из корзины на совсем для старосты

**Comment by dadyarri** [comment]
7 не понял для чего @ironalex2102

**Comment by ironalex2102** [comment]
Есть какой-то препод у группы, и ты хочешь посмотреть методички написанные именно им @dadyarri

**Comment by dadyarri** [comment]
> Есть какой-то препод у группы, и ты хочешь посмотреть методички написанные именно им @dadyarri

Эт получается лишнее поле "автора" добавлять... Но не у любого аттача может быть автор

**Comment by ironalex2102** [comment]
завтра обдумаем этот вопрос

**Comment by dadyarri** [comment]
6. что значат _поля_? Для чего нужен этот функционал?
8, 10. в текущей реализации события group-wide, придется переделывать схему

**Comment by Iogsothot** [comment]
11 удаление элемента в корзину или насовсем _[proc]_

**Comment by Iogsothot** [comment]
12 при прохождении теста идеально правильно выводить сообщении о том что  тесты созданы для пользоватлей

**Comment by Iogsothot** [comment]
jefSjo;AEFO"J

**Comment by Iogsothot** [comment]
14 при создании теста появляется ивент для группы что тест создан

**Comment by Iogsothot** [comment]
16 создание функции которая висит в воздухе и принимает и одает инфу о приходе/уходе предметов/преподов

**Comment by Iogsothot** [comment]
рпапоапоапоа

**Comment by dadyarri** [comment]
18. Получение списка студентов с контактами _[func]_

**Comment by Iogsothot** [comment]
19. изменение пароля пользователя _[proc]_

**Comment by dadyarri** [comment]
20. При удалении аккаунта старосты автоматически назначается старостой редактор с наибольшим числом предложений к изменению _[trig]_

**Comment by dadyarri** [comment]
21. получение списка студентов с данными об успеваемости _[func]_

**Comment by dadyarri** [comment]
22. вычисление процента, насколько текущий результат лучше прочих

**Comment by dadyarri** [comment]
23. соединение преподавателей и сотрудников [view]

**Comment by dadyarri** [comment]
24. получение списка методичек по предмету во всех семестрах _[func]_

**Comment by dadyarri** [comment]
25. создание уведомления при создании нового аттача _[proc]_

**Comment by dadyarri** [comment]
26. соединение сотрудников и групп _[view]_

**Comment by Iogsothot** [comment]
27. уведомление о появление нового софта _[trig]_

**Comment by dadyarri** [comment]
28. поиск предметов, которые ведёт преподаватель и подсчёт количества семестров у этих предметов _[func]_

**Comment by dadyarri** [comment]
29. статистика соотношения полов по направлению _[proc]_

**Comment by dadyarri** [comment]
30. ручное создание тестового пользователя _[proc]_

**Comment by dadyarri** [comment]
31. ручное создание тестовой группы _[proc]_

**Comment by dadyarri** [comment]
32. список вопросов по предмету _[view]_

**Comment by dadyarri** [comment]
Процедуры -- 9
Функции -- 11
Триггеры -- 10
Представления -- 3

**Comment by Iogsothot** [comment]
33. создание тестового специальность

**Comment by Iogsothot** [comment]
34.создание тестовый события
